mysite/books/urls.py
'''
Created on Feb 27, 2017

@author: Gergely
'''

from django.conf.urls import url

from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/books/2
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
]

mysite/books/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

#book table
# python.exe .\manage.py makemigrations books
# python.exe .\manage.py sqlmigrate books 0001
# python.exe .\manage.py migrate
# for shell access python.exe .\manage.py migrate
class Book(models.Model):
    
    def __str__(self):
        return self.name + '-' + self.author
    
    #field definitions
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    
    

mysite/books/views.py
# Create your views here.

from django.views import generic
from models import Book


class IndexView(generic.ListView):
    template_name = 'books/index.html'
    
    
    def get_queryset(self):
        return Book.objects.all()
    
    
class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'

mysite/books/templates/books/base.html
{% load staticfiles %}
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" >
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'books:index'%}">The Bookstore</a>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'books:index' %}">
						<span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Books
					</a>
				</li>	
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'books:index' %}">
						<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add Book
					</a>
				</li>
				<li class="">
					<a href="{% url 'books:index' %}">
						<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout
					</a>
				</li>		
			</ul>
		</div>
	</div>
	
</nav>

{% block body %}
{% endblock %}

</body>

</head>
</html>

mysite/books/templates/books/detail.html
{% extends 'books/base.html' %}

{% block body %}

<h1>{{book.name}}</h1>
<h4>{{book.author}}</h4>

{% endblock %}

mysite/books/templates/books/index.html
{% extends 'books/base.html' %}

{% block body %}
<html>
<head>
<!-- Latest compiled and minified CSS -->
</head>
<body>



<ul>
<!-- def get_queryset(self): return object list in views.py-->
 {% for book in object_list %}
 <li><a href="{% url 'books:detail' book.id %}">{{book.name}}</a></li>
 {% endfor %}
</ul>
</body>


</html>
{% endblock %}